### NO 1
Menulis deskripsi statistika (Descriptive Statistics) dari semua kolom pada data yang bersifat numerik, terdiri dari mean, median, modus, standar deviasi, variansi, range, nilai minimum, maksimum, kuartil, IQR, skewness dan kurtosis.

In [1]:
import pandas as pd
import numpy as np

col_names = ['id', 'pH', 'Hardness', 'Solids', 'Chloramines', 'Sulfate', 'Conductivity', 'OrganicCarbon', 'Trihalomethanes', 'Turbidity', 'Potability']
df = pd.read_csv('../data/water_potability.csv', names=col_names)
df = df.drop(["id", "Potability"], axis=1)

In [2]:
df.head()

,pH,Hardness,Solids,Chloramines,Sulfate,Conductivity,OrganicCarbon,Trihalomethanes,Turbidity
0,8.316766,214.373394,22018.417441,8.059332,356.886136,363.266516,18.436524,100.341674,4.628771
1,9.092223,181.101509,17978.986339,6.546600,310.135738,398.410813,11.558279,31.997993,4.075075
2,5.584087,188.313324,28748.687739,7.544869,326.678363,280.467916,8.399735,54.917862,2.559708
3,10.223862,248.071735,28749.716544,7.513408,393.663396,283.651634,13.789695,84.603556,2.672989
4,8.635849,203.361523,13672.091764,4.563009,303.309771,474.607645,12.363817,62.798309,4.401425

#### Menampilkan banyaknya data, rata - rata, standar deviasi, nilai minimal, nilai ketiga quartil serta nilai maksimal dari setiap kolom

In [3]:
df.describe()

,pH,Hardness,Solids,Chloramines,Sulfate,Conductivity,OrganicCarbon,Trihalomethanes,Turbidity
count,2010.000000,2010.000000,2010.000000,2010.000000,2010.000000,2010.000000,2010.000000,2010.000000,2010.000000
mean,7.087193,195.969209,21904.673439,7.134322,333.211376,426.476708,14.357940,66.400717,3.969497
std,1.572803,32.643166,8625.397911,1.585214,41.211111,80.701872,3.325770,16.081109,0.780471
min,0.227499,73.492234,320.942611,1.390871,129.000000,201.619737,2.200000,8.577013,1.450000
25%,6.090785,176.740657,15614.412962,6.138326,307.626986,366.619219,12.122530,55.949993,3.442882
50%,7.029490,197.203525,20926.882155,7.142014,332.214113,423.438372,14.323286,66.482041,3.967374
75%,8.053006,216.447589,27170.534649,8.109933,359.268147,482.209772,16.683562,77.294613,4.514663
max,14.000000,317.338124,56488.672413,13.127000,481.030642,753.342620,27.006707,124.000000,6.494749

#### Menampilkan modus dari data

In [4]:
df.mode()

,pH,Hardness,Solids,Chloramines,Sulfate,Conductivity,OrganicCarbon,Trihalomethanes,Turbidity
0,0.227499,73.492234,320.942611,1.390871,129.000000,201.619737,2.200000,8.577013,1.450000
1,0.989912,77.459586,1198.943699,1.920271,180.206746,210.319182,4.371899,14.343161,1.492207
2,1.431782,81.710895,1351.906979,2.397985,182.397370,233.907965,4.466772,15.684877,1.496101
3,1.757037,94.091307,1372.091043,2.456014,187.170714,245.859632,4.861631,16.291505,1.680554
4,1.985383,94.812545,2552.962804,2.458609,187.424131,252.968328,4.966862,17.527765,1.812529
...,...,...,...,...,...,...,...,...,...
2005,11.568768,286.567991,50793.898917,12.580026,458.441072,666.690618,23.569645,114.034946,6.307678
2006,11.898078,287.975540,53735.899194,12.626900,460.107069,669.725086,23.604298,114.208671,6.357439
2007,12.246928,300.292476,55334.702799,12.653362,475.737460,695.369528,23.917601,116.161622,6.389161
2008,13.349889,306.627481,56351.396304,13.043806,476.539717,708.226364,24.755392,120.030077,6.494249
2009,14.000000,317.338124,56488.672413,13.127000,481.030642,753.342620,27.006707,124.000000,6.494749

Interquartile range adalah selisih dari nilai Q3 dan Q1 yang biasanya digunakan untuk mengidentifikasi nilai pencilan

#### Berikut ditampilkan nilai Interquartile range dari setiap atribut

In [5]:
q1 = df.quantile(1/4)
q3 = df.quantile(3/4)
q3 - q1

pH                     1.962221
Hardness              39.706932
Solids             11556.121687
Chloramines            1.971607
Sulfate               51.641161
Conductivity         115.590553
OrganicCarbon          4.561031
Trihalomethanes       21.344620
Turbidity              1.071781
dtype: float64

Skewness dapat diartikan sebagai ukuran ketidaksimetrian suatu distribusi data. Skewness dapat bernilai positif, negatif, serta nol. Atribut yang memiliki nilai skewness positif artinya data berada lebih banyak disebelah kiri dibandingkan kanan karena ekor kurva berada pada sebelah kanan begitupula sebaliknya

#### Berikut ditampilkan nilai skewness dari setiap atribut

In [6]:
df.skew()

pH                 0.048535
Hardness          -0.085321
Solids             0.591011
Chloramines        0.013003
Sulfate           -0.045728
Conductivity       0.268012
OrganicCarbon     -0.020220
Trihalomethanes   -0.051383
Turbidity         -0.032266
dtype: float64

Kurtosis digunakan untuk menunjukan derajat keruncingan, semakin besar maka semakin runcing kurva tersebut. Nilai nol menunjukan data normal nilai positif menunjukan data semakin homogen serta nilai negatif menunjukan data semakin menyebar dan tidak homogen

#### Berikut ditampilkan nilai kurtosis dari setiap atribut

In [7]:
df.kurt()

pH                 0.626904
Hardness           0.525480
Solids             0.337320
Chloramines        0.549782
Sulfate            0.786854
Conductivity      -0.237206
OrganicCarbon      0.031018
Trihalomethanes    0.223017
Turbidity         -0.049831
dtype: float64

Kondisi ideal ketika nilai skewness bernilai nol serta nilai kurtosis bernilai 3. Kondisi ini menunjukan bahwa kurva terdistribusi secara normal. Dapat terlihat dari beberapa atribut yang ada pada bagian sebelumnya tidak ada kurva yang memiliki distribusi normal namun ada kurga yang memiliki nilai skewness yang nol artinya kurvanya normal